In [13]:
import pandas as pd #legal import btw
import matplotlib.pyplot as plt
import numpy as np

In [25]:
#ETL: E-Extract, T-Transform, L-Load

#Extract from .csv file first
df = pd.read_csv("./mariages_L3_5k.csv",encoding='utf-8',header=None)
df.columns = [
    'act_id', 'act_type',
    'person_a_last_name', 'person_a_first_name', 'person_a_father_first_name',
    'person_a_mother_last_name', 'person_a_mother_first_name',
    'person_b_last_name', 'person_b_first_name', 'person_b_father_first_name', 
    'person_b_mother_last_name', 'person_b_mother_first_name',
    'commune_name', 'department_id', 'act_date', 'view_number'
]

df

,act_id,act_type,person_a_last_name,person_a_first_name,person_a_father_first_name,person_a_mother_last_name,person_a_mother_first_name,person_b_last_name,person_b_first_name,person_b_father_first_name,person_b_mother_last_name,person_b_mother_first_name,commune_name,department_id,act_date,view_number
0,1,Mariage,ABADIE,Ferdinand Isidore,NaN,NaN,NaN,ANTIGNY,Esther Emilie,NaN,NaN,NaN,LUÇON,85,14/11/1876,48/210
1,2,Mariage,ABADIE,Ferdinand Isidore,NaN,NaN,NaN,MOREAU,Marie Malvina,NaN,NaN,NaN,LUÇON,85,15/06/1857,287/447
2,3,Mariage,ABADIE,Henri Louis François,NaN,NaN,NaN,GIRET,Marie Victoire Elise,NaN,NaN,NaN,SABLES D'OLONNE (LES),85,10/11/1891,33/179
3,4,Mariage,ABADIE,Jean Auguste,Jean François,MARTIN,Marie Rosalie,PLAIRE,Ursule Catherine Marie,Jean,MADE,Catherine,GRUES,85,11/09/1844,329/455
4,5,Mariage,ABADIE,Jean Baptiste,NaN,NaN,NaN,HURTAUD,Rose,NaN,NaN,NaN,TRIAIZE,85,17/10/1859,202/228
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4996,Mariage,ANGIBAUD,Pierre Julien,Pierre Julien +,MORICEAU,Perrine +,BARDET,Anne,Jean +,RENOUX,Françoise Marie +,SAINT PHILBERT DE BOUAINE,85,08/01/1814,125/424
4996,4997,Mariage,ANGIBAUD,Pierre Louis Joseph,Louis,GENAUDEAU,Marie Renée,LOUÉ,Louise Olive,Pierre Nicolas,GENAUDEAU,Perrine,VENANSAULT,85,27/01/1806,57/472
4997,4998,Mariage,ANGIBAUD,Pierre Louis Joseph,NaN,NaN,NaN,ROULEAU,Marie Radégonde Emélie Prudente Valentine,NaN,NaN,NaN,JARD (SUR MER),85,16/10/1816,42/381
4998,4999,Mariage,ANGIBAUD,Pierre Pasckal,NaN,NaN,NaN,GUYHEUX,Marie,NaN,NaN,NaN,TALMONT (SAINT HILAIRE),85,13/01/1824,156/248
4999,5000,Mariage,ANGIBAUD,Pierre Victor,Pierre,MAITRE,Louise,LEGUÉ,Mélanie Rose Clémantine,Pierre,ALLAIN,Françoise,CHAPELLE THÉMER (LA),85,09/07/1888,NaN

In [26]:
# Summary
df.astype('object').describe()

,act_id,act_type,person_a_last_name,person_a_first_name,person_a_father_first_name,person_a_mother_last_name,person_a_mother_first_name,person_b_last_name,person_b_first_name,person_b_father_first_name,person_b_mother_last_name,person_b_mother_first_name,commune_name,department_id,act_date,view_number
count,5000,5000,5000,4987,2443,2384,2392,4991,4985,2533,2480,2477,5000,5000,4672,4123
unique,5000,7,394,798,278,1157,292,2340,961,319,1356,345,375,4,4066,3813
top,1,Mariage,ALBERT,Pierre,Pierre,PIVETEAU,Marie,MOREAU,Marie,Jean,MOREAU,Marie,CHALLANS,85,24/02/1767,12/018
freq,1,4638,843,738,315,20,533,31,986,301,18,551,130,4534,6,5

In [27]:
# Count number of null(NaN) values for each column
df.isna().sum()

act_id                           0
act_type                         0
person_a_last_name               0
person_a_first_name             13
person_a_father_first_name    2557
person_a_mother_last_name     2616
person_a_mother_first_name    2608
person_b_last_name               9
person_b_first_name             15
person_b_father_first_name    2467
person_b_mother_last_name     2520
person_b_mother_first_name    2523
commune_name                     0
department_id                    0
act_date                       328
view_number                    877
dtype: int64

In [28]:
#Transform:
#idk what do we do?